---
site_name: "{{cookiecutter.project_name}}"
theme:
  name: material
  palette:
    # https://github.com/facelessuser/mkdocs_pymdownx_material_extras
    scheme: dracula
    primary: deep purple
    accent: deep purple
  features:
    - content.tabs.link

plugins:
  - search
  - mermaid2:
      # https://mkdocs-mermaid2.readthedocs.io/en/latest/library
      version: 10.9.0
  - mkdocs_pymdownx_material_extras

markdown_extensions:
  - pymdownx.superfences:
      # make exceptions to highlighting of code
      custom_fences:
        # activate display of Mermaid diagrams
        - name: mermaid
          class: mermaid
          # https://pypi.org/project/mkdocs-pymdownx-material-extras
          # https://mkdocs-mermaid2.readthedocs.io/en/latest/superfences
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md

site_url: https://{{cookiecutter.github_org}}.github.io/{{cookiecutter.project_name}}
repo_url: https://github.com/{{cookiecutter.github_org}}/{{cookiecutter.project_name}}

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
